name: proto_gen_ffi_bindings
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  ffi: ^0.1.3
  ffi_tool: ^0.2.2

#  path: ^1.6.0

dev_dependencies:
